## Configuration for the training, evaluation
samples:
  - name: RPV_1400
    label: 1
    path: ../data/RPV/Gluino1400GeV/*.h5
    xsec: 0.0252977
    ngen: 330599
  - name: QCD_HT700to1000
    label: 0
    path: ../data/QCD/HT700to1000/*.h5
    ignore: true
    xsec: 6831
    ngen: 0
  - name: QCD_HT1000to1500
    label: 0
    path: ../data/QCDBkg/HT1000to1500/*.h5
    xsec: 1207
    ngen: 15466225
  - name: QCD_HT1500to2000
    label: 0
    path: ../data/QCDBkg/HT1500to2000/*.h5
    xsec: 119.9
    ngen: 3368613
  - name: QCD_HT2000toInf
    label: 0
    path: ../data/QCDBkg/HT2000toInf/*.h5
    xsec: 25.24
    ngen: 3250016
  - name: ttbar               ## ttbar root file path : /store/hep/users/qoqorm/CMS_TTbar_80000/rootfile/PU   &&  file numbaer 1048, 1049, 1050, 1051, 1052 no use (no ['Delphes']) 
    label: 0
    path: ../data/ttbar/*.h5    
    xsec: 831.76
    ngen: 4204449
training:
    randomSeed1: 123456
    nDataLoaders: 16

